# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'millennial-3'

#google-ID: 'UA-112060364-2'

menu:
- {name: 'Artistes', folder: 'pages', file: 'artistes.html'}
- {name: 'Création', folder: 'pages', file: 'creation.html'}
- {name: 'Evénements', folder: 'pages', file: 'evenements.html'}
- {name: 'À propos', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:letazon@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Suivant'
  previous_page: 'Précédent'

sharing_button_prompt: 'Que du love si tu partages!'

related_posts: 'Peut être apprécierez vous...'

post_date_prefix: 'Ecrit le'
